### ISSUE TITLE
phase 1 - patch 3.0 - Naxxramas bug

### ISSUE THREAD

**Issue by mpfans** [Si1ker/WoltkProgression#1]
phase 1 - patch 3.0 - Naxxramas no weekly raid quests

patch 3.3 will have it

**Comment by mpfans** [comment]
https://wowpedia.fandom.com/wiki/Patch_3.3.0

`Daily Heroic and normal dungeon quests have been removed. These quests have been replaced with weekly raid quests (see the "Quests" section for details).`

`Quests
Weekly raid quests are now available from Archmage Lan'dalock in Dalaran. Every Tuesday at 3 AM the Council of Six will choose a different strategic target that must die from either: The Obsidian Sanctum, Naxxramas, The Eye of Eternity, Ulduar, Trial of the Crusader, or Icecrown Citadel.`

**Comment by Si1ker** [comment]
@mpfans your report is appreciated, this issue has been fixed in 5b0ec4c
The daily heroic and the four quests from "Timear Foresees" will be added into the patch 3.0 file as well and then removed in 3.3
Thank you.

**Comment by mpfans** [comment]
> @mpfans your report is appreciated, this issue has been fixed in [5b0ec4c](https://github.com/Si1ker/WoltkProgression/commit/5b0ec4c74b420610ce825e837981baf5345a1d85)
> The daily heroic and the four quests from "Timear Foresees" will be added into the patch 3.0 file as well and then removed in 3.3
> Thank you.

np,do you have discord? I have some progressive settings to discuss with you, because I have done a lot of work. Your progressive is not perfect

**Comment by mpfans** [comment]
@Si1ker
